{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example",
    "module": "external-bom",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "3.0"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "3.0"
          }
        }
      ]
    }
  ]
}
