{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example",
    "module": "bom-consumer",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.example",
          "module": "dragged-bom",
          "version": {
            "requires": "1.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.example",
          "module": "dragged-bom",
          "version": {
            "requires": "1.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        }
      ]
    }
  ]
}
