name: Update Gradle Wrapper

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.3.0

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.6

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.0

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1.0.18
